services:
  db:
    container_name: nawy-postgres
    image: postgis/postgis:latest
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nawy-db
      TZ: Africa/Cairo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nawy-network

  redis:
    container_name: nawy-redis
    image: redis
    restart: always
    ports:
      - "6399:6379"
    networks:
      - nawy-network

  backend:
    container_name: nawy-backend
    image: maespyramids/nawy-backend:2
    restart: always
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis
    networks:
      - nawy-network

  # frontend:
  #   container_name: nawy-frontend
  #   image: maespyramids/nextjs-app:latest
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - NEXT_PUBLIC_BACKEND_URL=http://localhost:3333
  #   depends_on:
  #     - backend
  #   networks:
  #     - nawy-network

volumes:
  postgres_data:
  redis_data:

networks:
  nawy-network:
    driver: bridge
