services:
  db:
    container_name: nawy-postgres
    image: postgis/postgis:latest
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nawy-db
      TZ: Africa/Cairo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: nawy-redis
    image: redis
    restart: always
    ports:
      - "6399:6379"

  backend:
    container_name: nawy-backend
    image: maespyramids/nawy-backend:2
    restart: always
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
